name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: New Release
        uses: cycjimmy/semantic-release-action@v2
        id: release # Need an `id` for output variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: 000000000000000
          GIT_AUTHOR_NAME: sudkumar
          GIT_AUTHOR_EMAIL: luckysud4@gmail.com
          GIT_COMMITTER_NAME: sudkumar
          GIT_COMMITTER_EMAIL: luckysud4@gmail.com
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
